### ISSUE TITLE
I cannot upload image on the Media file 

### ISSUE THREAD

**Issue by ahmxxd** [joschan21/digitalhippo#18]
Please I need your helps guys
I can't upload image file on media file, below is the err msg.

![Screenshot 2023-12-24 112042](https://github.com/joschan21/digitalhippo/assets/83852720/c82330fc-edbc-458b-9eb6-b5c4595cc84a)

**Comment by ahmxxd** [comment]
This is the err msg at the dev site

ERROR (payload): ValidationError: The following fields are invalid: mimeType, sizes.tablet.mimeType
    at beforeChange (C:\Users\hp\Desktop\binmarket\node_modules\payload\src\fields\hooks\beforeChange\index.ts:60:11)
    at async create (C:\Users\hp\Desktop\binmarket\node_modules\payload\src\collections\operations\create.ts:194:31)
    at async createHandler (C:\Users\hp\Desktop\binmarket\node_modules\payload\src\collections\requestHandlers\create.ts:26:17)
[10:20:13] ERROR (payload): ValidationError: The following fields are invalid: mimeType, sizes.tablet.mimeType

**Comment by ahmxxd** [comment]
Please I need help on the above issue

**Comment by coininstant** [comment]
It looks like the issue is you are trying to upload image_first.png.jpg When naming files, it's best to use a single, appropriate file extension that accurately represents the file format. If the file is a JPEG image, use ".jpg," and if it's a PNG image, use ".png."

**Comment by ahmxxd** [comment]
Thank you Sir
It works 
So great 

Sent from Yahoo Mail on Android 
 
  On Sun, Dec 31, 2023 at 5:15, Nicholas ***@***.***> wrote:   


It looks like the issue is you are trying to upload image_first.png.jpg When naming files, it's best to use a single, appropriate file extension that accurately represents the file format. If the file is a JPEG image, use ".jpg," and if it's a PNG image, use ".png."
