### ISSUE TITLE
[nodemon] failed to start process, "ts-node --project tsconfig.server.json src/server.ts -- -I" exec 

### ISSUE THREAD

**Issue by Phulieu** [joschan21/digitalhippo#40]
[nodemon] failed to start process, "ts-node --project tsconfig.server.json src/server.ts -- -I" exec not found
[nodemon] Error
    at Bus.<anonymous> (/Users/phulieu/Desktop/NextJS/cx2_tableTrader/digitalhippo/node_modules/nodemon/lib/nodemon.js:158:25)
    at Bus.emit (node:events:524:35)
    at ChildProcess.<anonymous> (/Users/phulieu/Desktop/NextJS/cx2_tableTrader/digitalhippo/node_modules/nodemon/lib/monitor/run.js:199:11)
    at ChildProcess.emit (node:events:512:28)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12)

**Comment by Phulieu** [comment]
using yarn start instead of yarn dev

**Comment by Phulieu** [comment]
need to yarn install -D ts-node

**Comment by sait-efe** [comment]
Thanks man
